input_assemblies: /shared/home/sbache/annotation_fusarium/assembly/snakemake_test/fasta_files/

ref: /shared/home/sbache/annotation_fusarium/assembly/snakemake_test/reference/UK0001.fasta

output_dir: /shared/home/sbache/annotation_fusarium/assembly/snakemake_test/output_dir/

lib: /shared/home/sbache/annotation_fusarium/assembly/snakemake_test/repeatmasker_lib/

dir_assemblies_renamed: /shared/home/sbache/annotation_fusarium/assembly/snakemake_test/fasta_renamed/

long_reads: /shared/home/sbache/annotation_fusarium/fastq_guppy5/

tapestry_dir: /shared/home/sbache/annotation_fusarium/assembly/snakemake_test/tapestry_output/

minimap2_dir: /shared/home/sbache/annotation_fusarium/assembly/snakemake_test/minimap2/
