#CONFIG FILE TEMPLATE FOR BWA MAPPING

#INPUT AND OUTPUT

DATA:
    REFERENCE: "/shared/home/tdurand/annotation_fijiensism2/assembly_worflow/ref/Mycfi2_wg_ed.fasta"
    ASSEMBLY: "/shared/home/tdurand/annotation_fijiensism2/assembly_worflow/souches_assemblage/"
    OUTPUT: "/shared/home/tdurand/annotation_fijiensism2/assembly_worflow/results/"

PARAMS_TOOLS:
    ATROPOS: "--minimum-length 35  -q 20,20  -U 8  -O 10"
    FASTQC: ""
    BWA_ALN: ""
    BWA_SAMPE: ""
    BWA_MEM: ""
    SAMTOOLS_VIEW: "-bh"
    SAMTOOLS_SORT: ""
    SAMTOOLS_DEPTH: ""
    PICARDTOOLS_MARK_DUPLICATES: "CREATE_INDEX=TRUE VALIDATION_STRINGENCY=SILENT"
    GATK_HAPLOTYPECALLER: "--emit-ref-confidence GVCF --output-mode EMIT_ALL_ACTIVE_SITES -ploidy 1"
    GATK_GENOMICSDBIMPORT: ""
    GATK_GENOTYPEGVCFS: "-new-qual"
    VCFTOOLS: ["--minDP 5 --minQ 30 --remove-indels --recode --recode-INFO-all --maf 0.05 --max-missing 0.7",
               "--minDP 20 --minQ 30 --remove-indels --recode --recode-INFO-all --maf 0.01 --max-missing 0.5"]
    RAXML: "-m GTRGAMMAX -f a -x $RANDOM -# autoMRE -p 600"
    RAXML_NG: "--all --model GTR+G --tree pars{50},rand{50} --bs-trees 100 --seed $RANDOM"
