DATA:
    REFERENCE: "./ref/Mycfi2_wg_ed.fasta"
    ASSEMBLY: "./CulebrONT_assembly_SUP/"
    OUTPUT: "./FIJIENSIS_ASSEMBLY_FINDER/RESULTS/"
    LONG_READS: "./fastq_guppy6/"
    REPEAT_DB: "./P_Fijiensis-families.fa"
    SHORT_READS : "./illumina/"


TOOLS_PARAM:
    BUSCO_DATABASE: "capnodiales_odb10"
    QUAST : "--fragmented -m 3000"
    BUSCO : ""
    REMOVE_CONTIGS_TRESHOLD: "0.8"
    BWA_MEM: ""
    SAMTOOLS_VIEW: "-bh"
    SAMTOOLS_SORT: ""
    SAMTOOLS_DEPTH: ""
    REPEAT_MASKER: "-no_is -gff -pa 8"
    MINIMAP2_REF: "-ax map-ont"
    SAMTOOLS_VIEW_LONG_READ_REF: ""
    SAMTOOLS_SORT_LONG_READ_REF: ""
    SAMTOOLS_INDEX_LONG_READ: ""
    SNIFFLES: ""
    MINIMAP2_ASSEMBLY: "-ax map-ont"
    SAMTOOLS_VIEW_LONG_READ_ASSEMBLY: ""
    SAMTOOLS_SORT_LONG_READ_ASSEMBLY: ""
    SAMTOOLS_COVERAGE: ""
    NUCMER: ""
    ASSEMBLYTICS: "10000 50 10000" 
    TAPESTRY: "-t TAACCC TTAGGG -m 3000"
    DATABASE_REPEAT_MODELER: ""
    REPEATMODELER: "-pa 3"
    
